/// Flutter icons Blicons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Blicons
///      fonts:
///       - asset: fonts/Blicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Blicons {
  Blicons._();

  static const _kFontFam = 'Blicons';
  static const String? _kFontPkg = null;

  static const IconData bl_diagnosis = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bl_history = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bl_home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bl_tests = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bl_treatments = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bl_user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bl_vaccinations = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
